version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - /home/meu-barbeiro/.env
    environment:
      - NODE_ENV=development
