version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - /home/meu-barbeiro/.env
    environment:
      - NODE_ENV=production
    restart: always