version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
      - "80:80"
    env_file:
      - /home/meu-barbeiro/.env
    environment:
      - NODE_ENV=development
