version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: meu-barbeiro
    ports:
      - "80:80"
    env_file:
      - /home/meu-barbeiro/.env
    restart: always