version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: meubarbeiro-front
    ports:
      - "8080:80"
    env_file:
      - /home/meu-barbeiro/.env
    environment:
      - NODE_ENV=production
    restart: always